package index

import (
	"strconv"
	"strings"

	tree_sitter "github.com/tree-sitter/go-tree-sitter"

	"github.com/Lordymine/codegraph/internal/graph"
)

// rubyScope carries the lexical owner of declarations. Ruby's runtime constant
// lookup is dynamic, so these names describe only declarations spelled in source.
type rubyScope struct {
	name      string
	singleton bool
}

// walkRubyDefs extracts declarations that are explicit in Ruby source. It does
// not infer methods generated by Rails or Ruby metaprogramming.
func walkRubyDefs(root *tree_sitter.Node, src []byte, add addFn) {
	walkRubyChildren(root, src, rubyScope{}, add)
}

func walkRubyChildren(parent *tree_sitter.Node, src []byte, scope rubyScope, add addFn) {
	for i := uint(0); i < parent.NamedChildCount(); i++ {
		n := parent.NamedChild(i)
		switch n.Kind() {
		case "class", "module":
			name := rubyNodeName(n.ChildByFieldName("name"), src)
			if name == "" {
				continue
			}
			qualified := rubyQualifiedScope(scope.name, name)
			label := graph.LabelClass
			if n.Kind() == "module" {
				label = graph.LabelModule
			}
			add(label, name, qualified, n.StartPosition().Row, n.EndPosition().Row,
				map[string]any{"is_exported": true})
			if body := n.ChildByFieldName("body"); body != nil {
				walkRubyChildren(body, src, rubyScope{name: qualified}, add)
			}

		case "singleton_class":
			if body := n.ChildByFieldName("body"); body != nil {
				owner := rubyNodeName(n.ChildByFieldName("value"), src)
				if owner == "self" {
					owner = scope.name
				}
				walkRubyChildren(body, src, rubyScope{name: owner, singleton: true}, add)
			}

		case "method":
			walkRubyMethod(n, src, scope, false, add)

		case "singleton_method":
			walkRubyMethod(n, src, scope, true, add)

		case "assignment":
			walkRubyConstant(n, src, scope, add)

		default:
			// Class and module declarations may appear inside conditionals. Descend
			// through non-declaration nodes, but never into a method body: a def
			// nested there is runtime-dependent and not a stable API declaration.
			walkRubyChildren(n, src, scope, add)
		}
	}
}

func walkRubyMethod(n *tree_sitter.Node, src []byte, scope rubyScope, explicitSingleton bool, add addFn) {
	name := rubyNodeName(n.ChildByFieldName("name"), src)
	if name == "" {
		return
	}
	owner := scope.name
	singleton := scope.singleton || explicitSingleton
	if explicitSingleton {
		receiver := rubyNodeName(n.ChildByFieldName("object"), src)
		if receiver != "" && receiver != "self" {
			owner = receiver
		}
	}
	label := graph.LabelMethod
	qualified := name
	if owner == "" {
		label = graph.LabelFunction
	} else if singleton {
		qualified = owner + "." + name
	} else {
		qualified = owner + "#" + name
	}
	add(label, name, qualified, n.StartPosition().Row, n.EndPosition().Row,
		map[string]any{"is_exported": true})
}

func walkRubyConstant(n *tree_sitter.Node, src []byte, scope rubyScope, add addFn) {
	name := rubyNodeName(n.ChildByFieldName("left"), src)
	if name == "" || !rubyConstantName(name) {
		return
	}
	qualified := rubyQualifiedScope(scope.name, name)
	add(graph.LabelConstant, name, qualified, n.StartPosition().Row, n.EndPosition().Row,
		map[string]any{"is_exported": true})
}

func rubyNodeName(n *tree_sitter.Node, src []byte) string {
	if n == nil {
		return ""
	}
	return n.Utf8Text(src)
}

func rubyQualifiedScope(owner, name string) string {
	name = strings.TrimPrefix(name, "::")
	if owner == "" || strings.Contains(name, "::") {
		return name
	}
	return owner + "::" + name
}

func rubyConstantName(name string) bool {
	name = strings.TrimPrefix(name, "::")
	if name == "" {
		return false
	}
	for _, part := range strings.Split(name, "::") {
		if part == "" || part[0] < 'A' || part[0] > 'Z' {
			return false
		}
	}
	return true
}

// walkRubyRoutes emits only direct Rails routing calls with a literal string
// path. Resourceful and dynamically constructed routes remain deliberately out
// of scope until a Rails-aware resolver can validate them.
func walkRubyRoutes(root *tree_sitter.Node, src []byte, relPath, project string, add addFn, addHandler func(string, string)) {
	if relPath != "config/routes.rb" {
		return
	}
	for _, block := range rubyRoutesDrawBlocks(root, src) {
		walkRubyRouteCalls(block, src, "", project, add, addHandler)
	}
}

func rubyRoutesDrawBlocks(root *tree_sitter.Node, src []byte) []*tree_sitter.Node {
	var blocks []*tree_sitter.Node
	var walk func(*tree_sitter.Node)
	walk = func(n *tree_sitter.Node) {
		if n.Kind() == "call" && rubyNodeName(n.ChildByFieldName("method"), src) == "draw" &&
			rubyNodeName(n.ChildByFieldName("receiver"), src) == "Rails.application.routes" {
			if block := n.ChildByFieldName("block"); block != nil {
				blocks = append(blocks, block)
			}
			return
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			walk(n.NamedChild(i))
		}
	}
	walk(root)
	return blocks
}

func walkRubyRouteCalls(root *tree_sitter.Node, src []byte, prefix, project string, add addFn, addHandler func(string, string)) {
	var walk func(*tree_sitter.Node)
	walk = func(n *tree_sitter.Node) {
		if path, handled, ok := rubyRouteScopePath(n, src); handled {
			if ok {
				if block := n.ChildByFieldName("block"); block != nil {
					walkRubyRouteCalls(block, src, rubyJoinRoutePath(prefix, path), project, add, addHandler)
				}
			}
			return
		}
		if routes, handled := rubyResourceRoutes(n, src, prefix); handled {
			for _, route := range routes {
				addRubyRoute(route.method, route.path, n, add)
			}
			return
		}
		if n.Kind() == "call" && n.ChildByFieldName("receiver") == nil {
			verb := rubyNodeName(n.ChildByFieldName("method"), src)
			if routeVerb, ok := rubyHTTPVerbs[verb]; ok {
				if path, ok := rubyLiteralRoutePath(n.ChildByFieldName("arguments"), src); ok {
					path = rubyJoinRoutePath(prefix, path)
					routeSuffix := addRubyRoute(routeVerb, path, n, add)
					if target, ok := rubyRouteHandlerTarget(n.ChildByFieldName("arguments"), src, project); ok {
						addHandler(routeSuffix, target)
					}
				}
			}
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			walk(n.NamedChild(i))
		}
	}
	walk(root)
}

type rubyResourceRoute struct{ method, path string }

var rubyPluralResourceActions = map[string][]rubyResourceRoute{
	"index": {{"GET", ""}}, "create": {{"POST", ""}}, "new": {{"GET", "/new"}},
	"show": {{"GET", "/:id"}}, "edit": {{"GET", "/:id/edit"}},
	"update": {{"PATCH", "/:id"}, {"PUT", "/:id"}}, "destroy": {{"DELETE", "/:id"}},
}

var rubySingularResourceActions = map[string][]rubyResourceRoute{
	"create": {{"POST", ""}}, "new": {{"GET", "/new"}}, "show": {{"GET", ""}},
	"edit": {{"GET", "/edit"}}, "update": {{"PATCH", ""}, {"PUT", ""}}, "destroy": {{"DELETE", ""}},
}

// rubyResourceRoutes expands only a single, literal, non-nested Rails resource.
// Unknown or dynamic options skip the subtree rather than emit a wrong route.
func rubyResourceRoutes(n *tree_sitter.Node, src []byte, prefix string) ([]rubyResourceRoute, bool) {
	if n.Kind() != "call" || n.ChildByFieldName("receiver") != nil {
		return nil, false
	}
	method := rubyNodeName(n.ChildByFieldName("method"), src)
	if method != "resources" && method != "resource" {
		return nil, false
	}
	args := n.ChildByFieldName("arguments")
	if args == nil || args.NamedChildCount() == 0 {
		return nil, true
	}
	name, ok := rubyResourceName(args.NamedChild(0), src)
	if !ok {
		return nil, true
	}
	for i := uint(1); i < args.NamedChildCount(); i++ {
		if args.NamedChild(i).Kind() != "pair" {
			return nil, true
		}
	}
	path := name
	if value := rubyResourceOption(args, src, "path"); value != nil {
		path, ok = rubyLiteralStringNode(value, src)
		if !ok || path == "" {
			return nil, true
		}
	}
	actions := rubyPluralResourceActions
	if method == "resource" {
		actions = rubySingularResourceActions
	}
	selected, ok := rubyResourceActions(args, src, actions)
	if !ok {
		return nil, true
	}
	newName, editName, ok := rubyResourcePathNames(args, src)
	if !ok {
		return nil, true
	}
	var out []rubyResourceRoute
	for action, routes := range actions {
		if !selected[action] {
			continue
		}
		for _, route := range routes {
			suffix := route.path
			if suffix == "/new" {
				suffix = "/" + newName
			}
			if suffix == "/edit" {
				suffix = "/" + editName
			}
			if suffix == "/:id/edit" {
				suffix = "/:id/" + editName
			}
			out = append(out, rubyResourceRoute{route.method, rubyJoinRoutePath(prefix, "/"+path+suffix)})
		}
	}
	return out, true
}

func rubyResourceName(n *tree_sitter.Node, src []byte) (string, bool) {
	if n != nil && n.Kind() == "simple_symbol" {
		return strings.TrimPrefix(rubyNodeName(n, src), ":"), true
	}
	return rubyLiteralStringNode(n, src)
}

func rubyResourceOption(args *tree_sitter.Node, src []byte, name string) *tree_sitter.Node {
	// Named child 0 is the resource name; options begin at child 1.
	for i := uint(1); i < args.NamedChildCount(); i++ {
		pair := args.NamedChild(i)
		if pair.Kind() == "pair" && rubyRouteOptionKey(pair.ChildByFieldName("key"), src) == name {
			return pair.ChildByFieldName("value")
		}
	}
	return nil
}

func rubyResourceActions(args *tree_sitter.Node, src []byte, available map[string][]rubyResourceRoute) (map[string]bool, bool) {
	selected := map[string]bool{}
	for action := range available {
		selected[action] = true
	}
	for _, option := range []string{"only", "except"} {
		value := rubyResourceOption(args, src, option)
		if value == nil {
			continue
		}
		actions, ok := rubyResourceActionList(value, src)
		if !ok {
			return nil, false
		}
		if option == "only" {
			selected = map[string]bool{}
		}
		for _, action := range actions {
			if _, ok := available[action]; !ok {
				// An unknown action makes the declaration ambiguous; skip it entirely.
				return nil, false
			}
			selected[action] = option == "only"
		}
	}
	return selected, true
}

func rubyResourceActionList(n *tree_sitter.Node, src []byte) ([]string, bool) {
	if n == nil {
		return nil, false
	}
	if n.Kind() == "simple_symbol" {
		return []string{strings.TrimPrefix(rubyNodeName(n, src), ":")}, true
	}
	if n.Kind() != "array" {
		return nil, false
	}
	var actions []string
	for i := uint(0); i < n.NamedChildCount(); i++ {
		action, ok := rubyResourceActionList(n.NamedChild(i), src)
		if !ok || len(action) != 1 {
			return nil, false
		}
		actions = append(actions, action[0])
	}
	return actions, true
}

func rubyResourcePathNames(args *tree_sitter.Node, src []byte) (newName, editName string, ok bool) {
	newName, editName = "new", "edit"
	value := rubyResourceOption(args, src, "path_names")
	if value == nil {
		return newName, editName, true
	}
	if value.Kind() != "hash" {
		return "", "", false
	}
	for i := uint(0); i < value.NamedChildCount(); i++ {
		pair := value.NamedChild(i)
		key := rubyRouteOptionKey(pair.ChildByFieldName("key"), src)
		if key != "new" && key != "edit" {
			// Other path_names entries do not affect REST paths emitted here.
			continue
		}
		name, valid := rubyLiteralStringNode(pair.ChildByFieldName("value"), src)
		if !valid || name == "" {
			return "", "", false
		}
		if key == "new" {
			newName = name
		} else {
			editName = name
		}
	}
	return newName, editName, true
}

func addRubyRoute(method, path string, n *tree_sitter.Node, add addFn) string {
	qn := "route." + method + "." +
		strings.ReplaceAll(strings.Trim(path, "/"), "/", ".") + "." +
		strconv.Itoa(int(n.StartPosition().Row)+1)
	add(graph.LabelRoute, method+" "+path, qn,
		n.StartPosition().Row, n.EndPosition().Row,
		map[string]any{"method": method, "path": path, "framework": "rails"})
	return qn
}

func rubyRouteHandlerTarget(args *tree_sitter.Node, src []byte, project string) (string, bool) {
	if args == nil {
		return "", false
	}
	for i := uint(0); i < args.NamedChildCount(); i++ {
		pair := args.NamedChild(i)
		if pair.Kind() != "pair" || rubyRouteOptionKey(pair.ChildByFieldName("key"), src) != "to" {
			continue
		}
		target, ok := rubyLiteralStringNode(pair.ChildByFieldName("value"), src)
		if !ok {
			return "", false
		}
		parts := strings.Split(target, "#")
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return "", false
		}
		segments := strings.Split(parts[0], "/")
		var classes []string
		for _, segment := range segments {
			classes = append(classes, rubyControllerClass(segment))
		}
		file := "app/controllers/" + strings.Join(segments, "/") + "_controller.rb"
		return project + ":" + file + "." + strings.Join(classes, "::") + "Controller#" + parts[1], true
	}
	return "", false
}

func rubyControllerClass(name string) string {
	var parts []string
	for _, part := range strings.Split(name, "_") {
		if part != "" {
			parts = append(parts, strings.ToUpper(part[:1])+part[1:])
		}
	}
	return strings.Join(parts, "")
}

// rubyRouteScopePath recognizes only route DSL scopes with a statically known URL
// prefix. A dynamic prefix makes every nested path ambiguous, so its subtree is skipped.
func rubyRouteScopePath(n *tree_sitter.Node, src []byte) (path string, handled, ok bool) {
	if n.Kind() != "call" || n.ChildByFieldName("receiver") != nil || n.ChildByFieldName("block") == nil {
		return "", false, false
	}
	method := rubyNodeName(n.ChildByFieldName("method"), src)
	args := n.ChildByFieldName("arguments")
	switch method {
	case "namespace":
		if path, present, ok := rubyRoutePathOption(args, src); present {
			return path, true, ok
		}
		if args == nil || args.NamedChildCount() == 0 {
			// namespace needs a name. Do not infer an empty URL prefix from invalid DSL.
			return "", true, false
		}
		return rubyLiteralRouteScopeName(args.NamedChild(0), src)
	case "scope":
		return rubyScopeRoutePath(args, src)
	default:
		return "", false, false
	}
}

func rubyLiteralRouteScopeName(n *tree_sitter.Node, src []byte) (string, bool, bool) {
	if path, ok := rubyLiteralRoutePathNode(n, src); ok {
		return path, true, true
	}
	if n != nil && n.Kind() == "simple_symbol" {
		name := strings.TrimPrefix(rubyNodeName(n, src), ":")
		if name != "" {
			return "/" + name, true, true
		}
	}
	return "", true, false
}

func rubyScopeRoutePath(args *tree_sitter.Node, src []byte) (string, bool, bool) {
	if args == nil || args.NamedChildCount() == 0 {
		return "", true, true
	}
	if path, present, ok := rubyRoutePathOption(args, src); present {
		return path, true, ok
	}
	first := args.NamedChild(0)
	if first.Kind() != "pair" {
		return rubyLiteralRouteScopeName(first, src)
	}
	return "", true, true
}

func rubyRoutePathOption(args *tree_sitter.Node, src []byte) (path string, present, ok bool) {
	if args == nil {
		return "", false, false
	}
	for i := uint(0); i < args.NamedChildCount(); i++ {
		pair := args.NamedChild(i)
		if pair.Kind() != "pair" || rubyRouteOptionKey(pair.ChildByFieldName("key"), src) != "path" {
			continue
		}
		if path, ok := rubyLiteralRoutePathNode(pair.ChildByFieldName("value"), src); ok {
			return path, true, true
		}
		return "", true, false
	}
	return "", false, false
}

func rubyRouteOptionKey(key *tree_sitter.Node, src []byte) string {
	if key == nil || key.Kind() != "hash_key_symbol" {
		return ""
	}
	return rubyNodeName(key, src)
}

func rubyJoinRoutePath(prefix, path string) string {
	return "/" + strings.Trim(strings.Trim(prefix, "/")+"/"+strings.Trim(path, "/"), "/")
}

var rubyHTTPVerbs = map[string]string{
	"get": "GET", "post": "POST", "put": "PUT", "patch": "PATCH",
	"delete": "DELETE", "head": "HEAD", "options": "OPTIONS",
}

func rubyLiteralRoutePath(args *tree_sitter.Node, src []byte) (string, bool) {
	if args == nil || args.NamedChildCount() == 0 {
		return "", false
	}
	return rubyLiteralRoutePathNode(args.NamedChild(0), src)
}

func rubyLiteralRoutePathNode(path *tree_sitter.Node, src []byte) (string, bool) {
	value, ok := rubyLiteralStringNode(path, src)
	if !ok {
		return "", false
	}
	if value == "" {
		return "", false
	}
	return "/" + strings.TrimPrefix(value, "/"), true
}

func rubyLiteralStringNode(n *tree_sitter.Node, src []byte) (string, bool) {
	if n == nil || n.Kind() != "string" || n.NamedChildCount() != 1 || n.NamedChild(0).Kind() != "string_content" {
		return "", false
	}
	return n.NamedChild(0).Utf8Text(src), true
}
