package index

import (
	"strconv"
	"strings"

	tree_sitter "github.com/tree-sitter/go-tree-sitter"

	"github.com/Lordymine/codegraph/internal/graph"
)

// rubyScope carries the lexical owner of declarations. Ruby's runtime constant
// lookup is dynamic, so these names describe only declarations spelled in source.
type rubyScope struct {
	name      string
	singleton bool
}

// walkRubyDefs extracts declarations that are explicit in Ruby source. It does
// not infer methods generated by Rails or Ruby metaprogramming.
func walkRubyDefs(root *tree_sitter.Node, src []byte, add addFn) {
	walkRubyChildren(root, src, rubyScope{}, add)
}

func walkRubyChildren(parent *tree_sitter.Node, src []byte, scope rubyScope, add addFn) {
	for i := uint(0); i < parent.NamedChildCount(); i++ {
		n := parent.NamedChild(i)
		switch n.Kind() {
		case "class", "module":
			name := rubyNodeName(n.ChildByFieldName("name"), src)
			if name == "" {
				continue
			}
			qualified := rubyQualifiedScope(scope.name, name)
			label := graph.LabelClass
			if n.Kind() == "module" {
				label = graph.LabelModule
			}
			add(label, name, qualified, n.StartPosition().Row, n.EndPosition().Row,
				map[string]any{"is_exported": true})
			if body := n.ChildByFieldName("body"); body != nil {
				walkRubyChildren(body, src, rubyScope{name: qualified}, add)
			}

		case "singleton_class":
			if body := n.ChildByFieldName("body"); body != nil {
				owner := rubyNodeName(n.ChildByFieldName("value"), src)
				if owner == "self" {
					owner = scope.name
				}
				walkRubyChildren(body, src, rubyScope{name: owner, singleton: true}, add)
			}

		case "method":
			walkRubyMethod(n, src, scope, false, add)

		case "singleton_method":
			walkRubyMethod(n, src, scope, true, add)

		case "assignment":
			walkRubyConstant(n, src, scope, add)

		default:
			// Class and module declarations may appear inside conditionals. Descend
			// through non-declaration nodes, but never into a method body: a def
			// nested there is runtime-dependent and not a stable API declaration.
			walkRubyChildren(n, src, scope, add)
		}
	}
}

func walkRubyMethod(n *tree_sitter.Node, src []byte, scope rubyScope, explicitSingleton bool, add addFn) {
	name := rubyNodeName(n.ChildByFieldName("name"), src)
	if name == "" {
		return
	}
	owner := scope.name
	singleton := scope.singleton || explicitSingleton
	if explicitSingleton {
		receiver := rubyNodeName(n.ChildByFieldName("object"), src)
		if receiver != "" && receiver != "self" {
			owner = receiver
		}
	}
	label := graph.LabelMethod
	qualified := name
	if owner == "" {
		label = graph.LabelFunction
	} else if singleton {
		qualified = owner + "." + name
	} else {
		qualified = owner + "#" + name
	}
	add(label, name, qualified, n.StartPosition().Row, n.EndPosition().Row,
		map[string]any{"is_exported": true})
}

func walkRubyConstant(n *tree_sitter.Node, src []byte, scope rubyScope, add addFn) {
	name := rubyNodeName(n.ChildByFieldName("left"), src)
	if name == "" || !rubyConstantName(name) {
		return
	}
	qualified := rubyQualifiedScope(scope.name, name)
	add(graph.LabelConstant, name, qualified, n.StartPosition().Row, n.EndPosition().Row,
		map[string]any{"is_exported": true})
}

func rubyNodeName(n *tree_sitter.Node, src []byte) string {
	if n == nil {
		return ""
	}
	return n.Utf8Text(src)
}

func rubyQualifiedScope(owner, name string) string {
	name = strings.TrimPrefix(name, "::")
	if owner == "" || strings.Contains(name, "::") {
		return name
	}
	return owner + "::" + name
}

func rubyConstantName(name string) bool {
	name = strings.TrimPrefix(name, "::")
	if name == "" {
		return false
	}
	for _, part := range strings.Split(name, "::") {
		if part == "" || part[0] < 'A' || part[0] > 'Z' {
			return false
		}
	}
	return true
}

// walkRubyRoutes emits only direct Rails routing calls with a literal string
// path. Resourceful and dynamically constructed routes remain deliberately out
// of scope until a Rails-aware resolver can validate them.
func walkRubyRoutes(root *tree_sitter.Node, src []byte, relPath string, add addFn) {
	if relPath != "config/routes.rb" {
		return
	}
	for _, block := range rubyRoutesDrawBlocks(root, src) {
		walkRubyRouteCalls(block, src, add)
	}
}

func rubyRoutesDrawBlocks(root *tree_sitter.Node, src []byte) []*tree_sitter.Node {
	var blocks []*tree_sitter.Node
	var walk func(*tree_sitter.Node)
	walk = func(n *tree_sitter.Node) {
		if n.Kind() == "call" && rubyNodeName(n.ChildByFieldName("method"), src) == "draw" &&
			rubyNodeName(n.ChildByFieldName("receiver"), src) == "Rails.application.routes" {
			if block := n.ChildByFieldName("block"); block != nil {
				blocks = append(blocks, block)
			}
			return
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			walk(n.NamedChild(i))
		}
	}
	walk(root)
	return blocks
}

func walkRubyRouteCalls(root *tree_sitter.Node, src []byte, add addFn) {
	var walk func(*tree_sitter.Node)
	walk = func(n *tree_sitter.Node) {
		if n.Kind() == "call" && n.ChildByFieldName("receiver") == nil {
			verb := rubyNodeName(n.ChildByFieldName("method"), src)
			if routeVerb, ok := rubyHTTPVerbs[verb]; ok {
				if path, ok := rubyLiteralRoutePath(n.ChildByFieldName("arguments"), src); ok {
					add(graph.LabelRoute, routeVerb+" "+path,
						"route."+routeVerb+"."+strings.ReplaceAll(strings.Trim(path, "/"), "/", ".")+"."+strconv.Itoa(int(n.StartPosition().Row)+1),
						n.StartPosition().Row, n.EndPosition().Row,
						map[string]any{"method": routeVerb, "path": path, "framework": "rails"})
				}
			}
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			walk(n.NamedChild(i))
		}
	}
	walk(root)
}

var rubyHTTPVerbs = map[string]string{
	"get": "GET", "post": "POST", "put": "PUT", "patch": "PATCH",
	"delete": "DELETE", "head": "HEAD", "options": "OPTIONS",
}

func rubyLiteralRoutePath(args *tree_sitter.Node, src []byte) (string, bool) {
	if args == nil || args.NamedChildCount() == 0 {
		return "", false
	}
	path := args.NamedChild(0)
	if path.Kind() != "string" || path.NamedChildCount() != 1 || path.NamedChild(0).Kind() != "string_content" {
		return "", false
	}
	value := path.NamedChild(0).Utf8Text(src)
	if value == "" {
		return "", false
	}
	return "/" + strings.TrimPrefix(value, "/"), true
}
